Classify errors as external when creating an Iceberg table
When creating an Iceberg table fails, for example with a permission
error, it should be classified as an external error, not internal
generic error.

Example stacktrace:
```
java.io.UncheckedIOException: Failed to create file: /var/folders/h6/n2g1k82s6rgcw5ghnf1lmgd00000gn/T/bf851f5f-7a4c-4df7-bcd9-e4f5062a09cb/iceberg_data/tpch/aa2-ca347f7732ef40bbb660c1fb6fe96007/metadata/snap-6360407032692364376-1-ce8e960b-f0f0-4db7-a63a-c071a0b5e62d.avro
	at io.trino.plugin.iceberg.fileio.ForwardingOutputFile.create(ForwardingOutputFile.java:50)
	at io.trino.plugin.iceberg.fileio.ForwardingOutputFile.createOrOverwrite(ForwardingOutputFile.java:58)
	at org.apache.iceberg.avro.AvroFileAppender.<init>(AvroFileAppender.java:56)
	at org.apache.iceberg.avro.Avro$WriteBuilder.build(Avro.java:197)
	at org.apache.iceberg.ManifestListWriter$V2Writer.newAppender(ManifestListWriter.java:100)
	at org.apache.iceberg.ManifestListWriter.<init>(ManifestListWriter.java:35)
	at org.apache.iceberg.ManifestListWriter.<init>(ManifestListWriter.java:31)
	at org.apache.iceberg.ManifestListWriter$V2Writer.<init>(ManifestListWriter.java:77)
	at org.apache.iceberg.ManifestLists.write(ManifestLists.java:67)
	at org.apache.iceberg.SnapshotProducer.apply(SnapshotProducer.java:241)
	at org.apache.iceberg.SnapshotProducer.lambda$commit$2(SnapshotProducer.java:386)
	at org.apache.iceberg.util.Tasks$Builder.runTaskWithRetry(Tasks.java:413)
	at org.apache.iceberg.util.Tasks$Builder.runSingleThreaded(Tasks.java:219)
	at org.apache.iceberg.util.Tasks$Builder.run(Tasks.java:203)
	at org.apache.iceberg.util.Tasks$Builder.run(Tasks.java:196)
	at org.apache.iceberg.SnapshotProducer.commit(SnapshotProducer.java:384)
	at io.trino.plugin.iceberg.IcebergUtil.commit(IcebergUtil.java:970)
	at io.trino.plugin.iceberg.IcebergMetadata.finishCreateTable(IcebergMetadata.java:1040)
	at io.trino.plugin.iceberg.IcebergMetadata.createTable(IcebergMetadata.java:911)
	at io.trino.plugin.base.classloader.ClassLoaderSafeConnectorMetadata.createTable(ClassLoaderSafeConnectorMetadata.java:450)
	at io.trino.tracing.TracingConnectorMetadata.createTable(TracingConnectorMetadata.java:386)
	at io.trino.metadata.MetadataManager.createTable(MetadataManager.java:837)
	at io.trino.tracing.TracingMetadata.createTable(TracingMetadata.java:410)
	at io.trino.execution.CreateTableTask.internalExecute(CreateTableTask.java:297)
	at io.trino.execution.CreateTableTask.execute(CreateTableTask.java:126)
	at io.trino.execution.CreateTableTask.execute(CreateTableTask.java:92)
	at io.trino.execution.DataDefinitionExecution.start(DataDefinitionExecution.java:146)
	at io.trino.execution.SqlQueryManager.createQuery(SqlQueryManager.java:272)
	at io.trino.dispatcher.LocalDispatchQuery.startExecution(LocalDispatchQuery.java:150)
	at io.trino.dispatcher.LocalDispatchQuery.lambda$waitForMinimumWorkers$2(LocalDispatchQuery.java:134)
	at io.airlift.concurrent.MoreFutures.lambda$addSuccessCallback$12(MoreFutures.java:570)
	at io.airlift.concurrent.MoreFutures$3.onSuccess(MoreFutures.java:545)
	at com.google.common.util.concurrent.Futures$CallbackListener.run(Futures.java:1137)
	at io.trino.$gen.Trino_testversion____20240828_151302_71.run(Unknown Source)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1144)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:642)
	at java.base/java.lang.Thread.run(Thread.java:1570)
Caused by: java.io.IOException: Creation of file /var/folders/h6/n2g1k82s6rgcw5ghnf1lmgd00000gn/T/bf851f5f-7a4c-4df7-bcd9-e4f5062a09cb/iceberg_data/tpch/aa2-ca347f7732ef40bbb660c1fb6fe96007/metadata/snap-6360407032692364376-1-ce8e960b-f0f0-4db7-a63a-c071a0b5e62d.avro failed: Mkdirs failed to create /var/folders/h6/n2g1k82s6rgcw5ghnf1lmgd00000gn/T/bf851f5f-7a4c-4df7-bcd9-e4f5062a09cb/iceberg_data/tpch/aa2-ca347f7732ef40bbb660c1fb6fe96007/metadata (exists=false, cwd=file:/Users/jwas/src/trino)
	at io.trino.filesystem.hdfs.HdfsOutputFile.create(HdfsOutputFile.java:108)
	at io.trino.filesystem.hdfs.HdfsOutputFile.create(HdfsOutputFile.java:62)
	at io.trino.filesystem.TrinoOutputFile.create(TrinoOutputFile.java:33)
	at io.trino.filesystem.tracing.TracingOutputFile.lambda$create$0(TracingOutputFile.java:47)
	at io.trino.filesystem.tracing.Tracing.withTracing(Tracing.java:47)
	at io.trino.filesystem.tracing.TracingOutputFile.create(TracingOutputFile.java:47)
	at io.trino.plugin.iceberg.fileio.ForwardingOutputFile.create(ForwardingOutputFile.java:47)
	... 36 more
Caused by: java.io.IOException: Mkdirs failed to create /var/folders/h6/n2g1k82s6rgcw5ghnf1lmgd00000gn/T/bf851f5f-7a4c-4df7-bcd9-e4f5062a09cb/iceberg_data/tpch/aa2-ca347f7732ef40bbb660c1fb6fe96007/metadata (exists=false, cwd=file:/Users/jwas/src/trino)
	at org.apache.hadoop.fs.ChecksumFileSystem.create(ChecksumFileSystem.java:724)
	at org.apache.hadoop.fs.ChecksumFileSystem.create(ChecksumFileSystem.java:709)
	at io.trino.hdfs.TrinoFileSystemCache$FileSystemWrapper.create(TrinoFileSystemCache.java:364)
	at org.apache.hadoop.fs.FileSystem.create(FileSystem.java:1229)
	at org.apache.hadoop.fs.FileSystem.create(FileSystem.java:1206)
	at org.apache.hadoop.fs.FileSystem.create(FileSystem.java:1087)
	at io.trino.filesystem.hdfs.HdfsOutputFile.lambda$create$1(HdfsOutputFile.java:100)
	at io.trino.hdfs.authentication.NoHdfsAuthentication.doAs(NoHdfsAuthentication.java:27)
	at io.trino.hdfs.HdfsEnvironment.doAs(HdfsEnvironment.java:134)
	at io.trino.filesystem.hdfs.HdfsOutputFile.create(HdfsOutputFile.java:115)
	at io.trino.filesystem.hdfs.HdfsOutputFile.create(HdfsOutputFile.java:100)
	... 42 more
```