Embed version once
For certain queries, embedded version would show up in stacktrace twice.

For example:

    presto> SELECT 1 / 0;
    Query 20200322_223738_00000_q5z3r failed: Division by zero
    io.prestosql.spi.PrestoException: Division by zero
            at io.prestosql.type.IntegerOperators.divide(IntegerOperators.java:106)
    ...
            at io.prestosql.sql.planner.iterative.rule.ExpressionRewriteRuleSet$ProjectExpressionRewrite.apply(ExpressionRewriteRuleSet.java:125)
            at io.prestosql.sql.planner.iterative.rule.ExpressionRewriteRuleSet$ProjectExpressionRewrite.apply(ExpressionRewriteRuleSet.java:106)
            at io.prestosql.sql.planner.iterative.IterativeOptimizer.transform(IterativeOptimizer.java:165)
    ...
            at io.prestosql.sql.planner.LogicalPlanner.plan(LogicalPlanner.java:180)
            at io.prestosql.execution.SqlQueryExecution.doPlanQuery(SqlQueryExecution.java:395)
            at io.prestosql.execution.SqlQueryExecution.planQuery(SqlQueryExecution.java:383)
            at io.prestosql.execution.SqlQueryExecution.start(SqlQueryExecution.java:338)
            at io.prestosql.$gen.Presto_null__testversion____20200322_223351_2.run(Unknown Source)
            at io.prestosql.execution.SqlQueryManager.createQuery(SqlQueryManager.java:241)
            at io.prestosql.dispatcher.LocalDispatchQuery.lambda$startExecution$7(LocalDispatchQuery.java:132)
            at io.prestosql.$gen.Presto_null__testversion____20200322_223351_2.run(Unknown Source)
            at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
            at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
            at java.base/java.lang.Thread.run(Thread.java:834)
    Caused by: java.lang.ArithmeticException: / by zero
            at io.prestosql.type.IntegerOperators.divide(IntegerOperators.java:103)
            ... 48 more