Mark testUnionDistinctViews as `@Flaky`
Should alleviate failure like this

    2022-12-05 19:03:57 INFO: Test io.trino.tests.product.hive.TestHiveViews.testUnionDistinctViews took 38.65s
    2022-12-05 19:03:57 INFO: FAILURE     /    io.trino.tests.product.hive.TestHiveViews.testUnionDistinctViews (Groups: hive_views) took 39.2 seconds
    2022-12-05 19:03:57 SEVERE: Failure cause:
    io.trino.tempto.query.QueryExecutionException: java.sql.SQLException: Error while processing statement: FAILED: Execution Error, return code 1 from org.apache.hadoop.hive.ql.exec.mr.MapRedTask. Error caching map.xml: java.nio.channels.ClosedByInterruptException
            at io.trino.tempto.query.JdbcQueryExecutor.execute(JdbcQueryExecutor.java:119)
            at io.trino.tempto.query.JdbcQueryExecutor.executeQuery(JdbcQueryExecutor.java:84)
            at io.trino.tests.product.hive.AbstractTestHiveViews.assertViewQuery(AbstractTestHiveViews.java:729)
            at io.trino.tests.product.hive.AbstractTestHiveViews.testUnionDistinctViews(AbstractTestHiveViews.java:571)
            at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
            at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
            at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
            at java.base/java.lang.reflect.Method.invoke(Method.java:568)
            at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:104)
            at org.testng.internal.Invoker.invokeMethod(Invoker.java:645)
            at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:851)
            at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1177)
            at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:129)
            at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:112)
            at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
            at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
            at java.base/java.lang.Thread.run(Thread.java:833)
    Caused by: java.sql.SQLException: Error while processing statement: FAILED: Execution Error, return code 1 from org.apache.hadoop.hive.ql.exec.mr.MapRedTask. Error caching map.xml: java.nio.channels.ClosedByInterruptException
            at org.apache.hive.jdbc.HiveStatement.execute(HiveStatement.java:275)
            at io.trino.tempto.query.JdbcQueryExecutor.executeQueryNoParams(JdbcQueryExecutor.java:128)
            at io.trino.tempto.query.JdbcQueryExecutor.execute(JdbcQueryExecutor.java:112)
            ... 16 more
            Suppressed: java.lang.Exception: Query: SELECT r_regionkey FROM UNION_DISTINCT_view
                    at io.trino.tempto.query.JdbcQueryExecutor.executeQueryNoParams(JdbcQueryExecutor.java:136)
                    ... 17 more

Also, opportunistically mark testUnionAllViews as well.