Standardise on at.yawk.lz4:lz4-java 1.10.1
Replacing org.lz4:lz4-java 1.8.1and removing old transitive LZ4
dependencies from Kafka, Hadoop, Elasticsearch and Pinot.

This fixes classpath conflicts, addresses CVE-2025-66566, and resolves
NoClassDefFoundError: net/jpountz/lz4/LZ4Factory in trino-hive tests.

Signed-off-by: Stephen Curran  <stephen.curran@est.tech>