Remove ProtobufSchema from method signatures
Guice calls `Class#getDeclaredMethods` to discover the methods which
require injection of an argument. This makes all the classes present in
the method signature to get loaded.

In 02cc332319a00e8fec5096921f96cb9e0aceacc1 a new method was added whose
signature includes `ProtobufSchema` which is present in a Confluent
licensed library which Trino doesn't ship with. Since that commit the
Kafka connector startup fails with the following error message
regardless of whether or not Protobuf functionality is being used:

    2023-04-30T05:33:54.710Z    ERROR    main    io.trino.server.Server    io/confluent/kafka/schemaregistry/protobuf/ProtobufSchema
    java.lang.NoClassDefFoundError: io/confluent/kafka/schemaregistry/protobuf/ProtobufSchema
        at java.base/java.lang.Class.getDeclaredMethods0(Native Method)
        at java.base/java.lang.Class.privateGetDeclaredMethods(Class.java:3402)
        at java.base/java.lang.Class.getDeclaredMethods(Class.java:2504)
        at com.google.inject.internal.DeclaredMembers.getDeclaredMethods(DeclaredMembers.java:48)
        at com.google.inject.spi.InjectionPoint.getDeclaredMethods(InjectionPoint.java:811)
        at com.google.inject.spi.InjectionPoint.getInjectionPoints(InjectionPoint.java:730)
        at com.google.inject.spi.InjectionPoint.forInstanceMethodsAndFields(InjectionPoint.java:430)
        at com.google.inject.internal.ConstructorBindingImpl.getInternalDependencies(ConstructorBindingImpl.java:177)
        at com.google.inject.internal.InjectorImpl.getInternalDependencies(InjectorImpl.java:670)
        at com.google.inject.internal.InjectorImpl.cleanup(InjectorImpl.java:627)
        at com.google.inject.internal.InjectorImpl.initializeJitBinding(InjectorImpl.java:613)
        at com.google.inject.internal.InjectorImpl.createJustInTimeBinding(InjectorImpl.java:943)
        at com.google.inject.internal.InjectorImpl.createJustInTimeBindingRecursive(InjectorImpl.java:863)
        at com.google.inject.internal.InjectorImpl.getJustInTimeBinding(InjectorImpl.java:300)
        at com.google.inject.internal.InjectorImpl.getBindingOrThrow(InjectorImpl.java:223)
        at com.google.inject.internal.InjectorImpl.getInternalFactory(InjectorImpl.java:949)
        at com.google.inject.internal.FactoryProxy.notify(FactoryProxy.java:48)
        at com.google.inject.internal.ProcessedBindingData.runCreationListeners(ProcessedBindingData.java:60)
        at com.google.inject.internal.InternalInjectorCreator.initializeStatically(InternalInjectorCreator.java:137)
        at com.google.inject.internal.InternalInjectorCreator.build(InternalInjectorCreator.java:110)
        at com.google.inject.Guice.createInjector(Guice.java:87)
        at io.airlift.bootstrap.Bootstrap.initialize(Bootstrap.java:268)
        at io.trino.plugin.kafka.KafkaConnectorFactory.create(KafkaConnectorFactory.java:71)
        at io.trino.connector.DefaultCatalogFactory.createConnector(DefaultCatalogFactory.java:221)
        at io.trino.connector.DefaultCatalogFactory.createCatalog(DefaultCatalogFactory.java:130)
        at io.trino.connector.LazyCatalogFactory.createCatalog(LazyCatalogFactory.java:45)
        at io.trino.connector.StaticCatalogManager.lambda$loadInitialCatalogs$1(StaticCatalogManager.java:158)
        at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
        at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:539)
        at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
        at com.google.common.util.concurrent.DirectExecutor.execute(DirectExecutor.java:31)
        at java.base/java.util.concurrent.ExecutorCompletionService.submit(ExecutorCompletionService.java:184)
        at io.trino.util.Executors.executeUntilFailure(Executors.java:41)
        at io.trino.connector.StaticCatalogManager.loadInitialCatalogs(StaticCatalogManager.java:152)
        at io.trino.server.Server.doStart(Server.java:144)
        at io.trino.server.Server.lambda$start$0(Server.java:91)
        at io.trino.$gen.Trino_415____20230430_053321_1.run(Unknown Source)
        at io.trino.server.Server.start(Server.java:91)
        at io.trino.server.TrinoServer.main(TrinoServer.java:38)
    Caused by: java.lang.ClassNotFoundException: io.confluent.kafka.schemaregistry.protobuf.ProtobufSchema
        at java.base/java.net.URLClassLoader.findClass(URLClassLoader.java:445)
        at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:587)
        at io.trino.server.PluginClassLoader.loadClass(PluginClassLoader.java:128)
        at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:520)
        ... 39 more

This change resolves the issue by changing the method signature to not
use a class which isn't always on the classpath.

The next commit introduces some safeguards to prevent other occurences
of this issue.