Fix thread-safety issue in ExtraCredentialsBasedIdentityCacheMapping
https://bugs.openjdk.org/browse/JDK-8009635
The MessageDigest API doesn't actually say implementations need to be
MT-safe, trying to do anything in this manner is fraught with
functional peril.

Within most of the other (if not all) usages of MessageDigest,
`getInstance` is used close to the `digest`, where it creates a new
instance for each invocation.

When multiple concurrent queries use extra credentials, threads race
on the shared `sha256` field and corrupt its internal buffer state,
producing:

  java.lang.ArrayIndexOutOfBoundsException: arraycopy: length -24 is negative