Add extra information on memory pool leaks
When we notice that at the there is memory leak from
DistributedQueryRunner after finishing up tests we print extra
information regarding memory pool and queries from the cluster, so it
is easier to pinpoint the problem in code.

Example output:
```
java.lang.AssertionError: Expected memory reservation on server_0(worker)to be 0 but was 5663866; detailed memory usage:
 20220304_183721_00001_2dtqj:
   SQL: SELECT count(*) FROM tpch.tiny.customer
   memoryReservation: 7428
   taggedMemoryReservaton: {AggregationOperator=408, ExchangeOperator=5184, LazyOutputBuffer=1836}
 20220304_183726_00029_2dtqj:
   SQL: SELECT TIMESTAMP '2017-01-02 09:12:34.123456789 Europe/Paris'
   memoryReservation: 113
   taggedMemoryReservaton: {LazyOutputBuffer=113}
```