Fix LZ4 ClassNotFoundException in trino-hive-formats
Add at.yawk.lz4:lz4-java dependency to replace excluded org.lz4:lz4-java
dependency that was causing NoClassDefFoundError: net/jpountz/lz4/LZ4Factory
in trino-hive tests.

Signed-off-by: Stephen Curran  <stephen.curran@est.tech>