Handle S3 paths where bucket name contains "dot digit"
`HadoopPaths` compatibility layer was failing when S3 bucket name
contains a dot followed by a digit:

```
java.net.URISyntaxException: Illegal character in hostname at index 10: s3://test.123/abc//xyz.csv#abc//xyz.csv
	at java.base/java.net.URI$Parser.fail(URI.java:2974)
	at java.base/java.net.URI$Parser.parseHostname(URI.java:3517)
	at java.base/java.net.URI$Parser.parseServer(URI.java:3358)
	at java.base/java.net.URI$Parser.parseAuthority(URI.java:3277)
	at java.base/java.net.URI$Parser.parseHierarchical(URI.java:3219)
	at java.base/java.net.URI$Parser.parse(URI.java:3175)
	at java.base/java.net.URI.<init>(URI.java:708)
	at java.base/java.net.URI.<init>(URI.java:809)
	at io.trino.filesystem.hdfs.HadoopPaths.toPathEncodedUri(HadoopPaths.java:46)
```

Using a different `URI` constructor avoids the problem.

(cherry picked from commit b825b965abc3b1301c50495ad9fbf832e09cbd12)